version: '2'

volumes:
  app:
  db:
  onlyoffice_data:
  onlyoffice_log:

networks:
  nextcloud:
    driver: 'bridge'

services:
  db:
    container_name: nextcloud-db
    image: mariadb
    restart: always
    volumes:
      - /mnt/nextcloud/mysql:/var/lib/mysql:delegated
    networks:
      - nextcloud
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - REDIS_HOST=redis

  app:
    container_name: nextcloud-app
    image: nextcloud:fpm
    links:
      - db
    volumes:
      - /mnt/nextcloud/data:/var/www/html:delegated
    restart: always
    networks:
      - nextcloud

  web:
    container_name: nextcloud-web
    image: nginx
    ports:
      - 5678:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    restart: always
    networks:
      - nextcloud

  onlyoffice-document-server:
    container_name: onlyoffice
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - nextcloud
    ports:
      - 5679:80
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data:delegated
      - onlyoffice_log:/var/log/onlyoffice:delegated

  redis:
    container_name: nextcloud-redis
    image: redis:5.0.7-alpine3.11
    restart: always
    networks:
      - nextcloud
    volumes:
      - /mnt/nextcloud/redis:/data:delegated
