version: '2.4'

volumes:
  app:
  db:
  onlyoffice_data:
  onlyoffice_log:

networks:
  nextcloud:
    driver: 'bridge'

services:
  db:
    container_name: nextcloud-db
    image: mariadb
    restart: always
    mem_limit: 1g
    cpu_percent: 50
    cpu_shares: 1024
    pids_limit: 50
    volumes:
      - /mnt/nextcloud/mysql:/var/lib/mysql:delegated
    networks:
      - nextcloud
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - REDIS_HOST=redis
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 45s
      interval: 30s
      retries: 5

  app:
    container_name: nextcloud-app
    image: nextcloud
    restart: always
    mem_limit: 1g
    cpu_percent: 50
    cpu_shares: 1024
    pids_limit: 100
    ports:
      - "127.0.0.1:5678:80"
    links:
      - db
    volumes:
      - /mnt/nextcloud/data:/var/www/html:delegated
    networks:
      - nextcloud
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost" ]
      timeout: 45s
      interval: 30s
      retries: 5

  onlyoffice-document-server:
    container_name: onlyoffice
    image: onlyoffice/documentserver:5.6
    stdin_open: true
    tty: true
    restart: always
    mem_limit: 1g
    cpu_percent: 50
    cpu_shares: 1024
    pids_limit: 200
    networks:
      - nextcloud
    ports:
      - "127.0.0.1:5679:80"
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data:delegated
      - onlyoffice_log:/var/log/onlyoffice:delegated

  redis:
    container_name: nextcloud-redis
    image: redis:5.0.7-alpine3.11
    restart: always
    mem_limit: 1g
    cpu_percent: 50
    cpu_shares: 1024
    pids_limit: 50
    networks:
      - nextcloud
    volumes:
      - /mnt/nextcloud/redis:/data:delegated
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      timeout: 45s
      interval: 30s
      retries: 5
